#!/usr/bin/env node
// Generates src/core/skills/generated/bundle.ts from the authored skills under skills/.
//
// The content must end up inside the JS bundle: npm publishes only dist/, and a SEA binary
// has no adjacent files at all.

import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import yaml from 'js-yaml';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = join(repoRoot, 'skills');
const outFile = join(repoRoot, 'src', 'core', 'skills', 'generated', 'bundle.ts');

const readMeta = async (name) => {
  const raw = await readFile(join(skillsDir, name, 'meta.yaml'), 'utf8');
  const meta = yaml.load(raw);

  if (typeof meta?.name !== 'string' || meta.name.length === 0) {
    throw new Error(`skills/${name}/meta.yaml: "name" is required`);
  }

  if (typeof meta?.description !== 'string' || meta.description.length === 0) {
    throw new Error(`skills/${name}/meta.yaml: "description" is required`);
  }

  if (meta.name !== name) {
    throw new Error(`skills/${name}/meta.yaml: "name" (${meta.name}) must match its directory`);
  }

  return meta;
};

const collect = async () => {
  const entries = await readdir(skillsDir, { withFileTypes: true });
  const skills = [];

  for (const entry of entries
    .filter((e) => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))) {
    const meta = await readMeta(entry.name);

    skills.push({
      name: meta.name,
      description: meta.description.trim(),
      body: (await readFile(join(skillsDir, entry.name, 'skill.md'), 'utf8')).trim(),
    });
  }

  if (skills.length === 0) {
    throw new Error('No skills found under skills/');
  }

  return skills;
};

const skills = await collect();
const { version } = JSON.parse(await readFile(join(repoRoot, 'package.json'), 'utf8'));

const source = `// GENERATED BY scripts/generate-skills.js — DO NOT EDIT.
// Run \`npm run generate:skills\` (or any build/dev/test script) to regenerate.

import type { Skill } from '../types.ts';

/** Version stamped into installed skill files, so a reinstall can recognize its own output. */
export const CLI_VERSION = ${JSON.stringify(version)};

export const SKILL_BUNDLE: readonly Skill[] = ${JSON.stringify(skills, null, 2)} as const;
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, source, 'utf8');

process.stderr.write(
  `generate-skills: wrote ${skills.length} skill(s) to src/core/skills/generated/bundle.ts\n`
);
